name: Compilar APK Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        run: flutter pub get

      # --- HABILITAR PLATAFORMA ANDROID ---
      - name: Habilitar plataforma Android
        run: flutter create . --platforms android

      # --- ETAPAS PARA O APK (ANDROID) ---
      - name: Gerar APK (Release)
        run: flutter build apk --release

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: app-familia-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
