name: Compilar APK Android e Deploy Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        run: flutter pub get

      # --- ETAPAS PARA O GITHUB PAGES (WEB) ---
      - name: Gerar Web (Release)
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Publicar no GitHub Pages
        uses: PeaceIris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

      # --- ETAPAS PARA O APK (ANDROID) ---
      - name: Gerar APK (Release)
        run: flutter build apk --split-per-abi --no-pub

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: app-familia-apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          
